openapi: 3.0.1
info:
  title: OrderAPI
  description: API Definition of OrderAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/order
paths:
  /:
    get:
      responses:
        default:
          description: Default response
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
  /{order}:
    get:
      parameters:
      - name: order
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: Default response
    delete:
      parameters:
      - name: order
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: Default response
    patch:
      parameters:
      - name: order
        in: path
        required: true
        schema:
          type: string
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
